//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingType
    {
        public BookingType()
        {
            this.ReservableSpaces = new HashSet<ReservableSpace>();
        }
    
        public int TypeID { get; set; }
        public string BookingDescription { get; set; }
    
        public virtual ICollection<ReservableSpace> ReservableSpaces { get; set; }
    }
}
