//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservableSpace
    {
        public ReservableSpace()
        {
            this.TicketedSpaceInts = new HashSet<TicketedSpaceInt>();
        }
    
        public int CompartmentSeatNumber { get; set; }
    
        public virtual BookingType BookingType { get; set; }
        public virtual Train Train { get; set; }
        public virtual ICollection<TicketedSpaceInt> TicketedSpaceInts { get; set; }
    }
}
