//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrainDataModelContainer : DbContext
    {
        public TrainDataModelContainer()
            : base("name=TrainDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Train> Trains { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<StopsAsc> StopsAscs { get; set; }
        public virtual DbSet<BookingType> BookingTypes { get; set; }
        public virtual DbSet<ReservableSpace> ReservableSpaces { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<Segment> Segments { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<TicketedSpaceInt> TicketedSpaceInts { get; set; }
    }
}
